<?php
return [
    'exclude_exact' => [
        'config.php',
        'default.php',
        'storage/.installed',
        'storage/.install-key',
        'storage/.install-probe',
        'storage/MAINTENANCE',
        'storage/.reset-pending',
        'robots.txt.bak',
    ],
    'exclude_prefixes' => [
        'dev/',
        'storage/logs/',
        'storage/cache/',
        'storage/sessions/',
        'storage/proofs/',
        'uploads/products/',
        'uploads/collections/',
        'uploads/og/',
        'uploads/settings/',
        '.git',
    ],
    'exclude_basenames' => ['.DS_Store', 'Thumbs.db', '.gitignore', '__MACOSX', 'cj.txt', 'cookies.txt'],
    'keep_inside_excluded_dirs' => ['.gitkeep', 'index.php', '.htaccess'],
    'include_prefixes' => ['uploads/products/sample/', 'uploads/og/sample/'],
    'seed_sql' => 'db/seed.sql',
    'seed_product_dir' => 'uploads/products/',
    'seed_product_og_dir' => 'uploads/og/',
    'seed_collection_dir' => 'uploads/',
    'seed_product_sizes' => ['thumb', 'card', 'zoom'],
    'seed_collection_sizes' => ['card', 'zoom'],
    'uploads_allowed_basenames' => ['.htaccess', 'index.html', '.gitkeep', 'index.php'],
    'empty_dirs' => [
        'storage/logs', 'storage/cache', 'storage/sessions', 'storage/sessions/shop', 'storage/sessions/admin', 'storage/proofs',
        'uploads/products', 'uploads/collections', 'uploads/og', 'uploads/settings',
    ],
    'required_files' => [
        'index.php', 'install.php', 'cron.php', '.htaccess', '.user.ini', 'config.sample.php', 'robots.txt', 'favicon.ico',
        'app/.htaccess', 'db/.htaccess', 'storage/.htaccess', 'uploads/.htaccess', 'assets/.htaccess', 'admin/.htaccess',
        'admin/controllers/.htaccess', 'admin/views/.htaccess', 'admin/partials/.htaccess',
        'assets/css/critical.css', 'assets/css/site.css', 'assets/css/admin.css', 'assets/js/css.js',
        'assets/css/motion.css', 'assets/js/motion/config.js', 'assets/js/motion/core.js', 'assets/js/motion/gate.js',
        'assets/js/vendor/gsap.min.js', 'assets/js/vendor/ScrollTrigger.min.js', 'assets/js/vendor/lenis.min.js',
        'assets/js/vendor/LICENSE-gsap.txt', 'assets/js/vendor/LICENSE-lenis.txt',
        'assets/js/intro.js', 'app/partials/intro.php', 'assets/img/brand/monogram-transparent-256.webp',
        'assets/fonts/cormorant-garamond-variable.woff2', 'assets/fonts/jost-variable.woff2',
        'app/bootstrap.php', 'admin/index.php', 'db/schema.sql', 'db/seed.sql', 'db/sample-manifest.php', 'app/data/default-copy.php',
        'storage/index.php', 'db/index.php', 'admin/controllers/index.php', 'admin/views/index.php', 'admin/partials/index.php',
        'app/lib/vendor/PHPMailer/PHPMailer.php', 'app/lib/vendor/PHPMailer/SMTP.php', 'app/lib/vendor/PHPMailer/Exception.php', 'app/lib/vendor/PHPMailer/LICENSE',
        'uploads/products/sample/azure-oud-1-card.webp', 'uploads/og/sample/azure-oud-1-og.jpg', 'uploads/collections/dawn-chorus-card.webp',
        'uploads/index.html',
        'app/tools/reset-password.php',
        'app/lib/theme.php',
        'assets/img/brand/monogram-gilt-256.png', 'assets/img/brand/monogram-gilt-256.webp', 'assets/img/brand/monogram-gilt-512.png',
        'assets/img/brand/lockup-transparent-800.webp', 'assets/img/brand/lockup-gilt-800.png', 'assets/img/brand/lockup-gilt-800.webp',
        'assets/img/placeholder-4x5-light.svg',
        'assets/img/motion/ribbons-a-light-540.webp', 'assets/img/motion/ribbons-a-light-960.webp',
        'assets/img/motion/ribbons-b-light-540.webp', 'assets/img/motion/ribbons-b-light-960.webp',
    ],
    'required_htaccess_count' => 10,
    'forbidden_patterns' => [
        '#^(dev/|\.git|storage/sessions/[^/]+/sess_|storage/logs/.+\.log$|storage/cache/.+\.(json|xml|php)$|storage/proofs/\d)#',
        '#(^|/)(config\.php|\.DS_Store|\.installed|\.install-key|\.install-probe|\.reset-pending|MAINTENANCE)$#',
        '#^storage/reset-[0-9a-f]{16}$#',
        '#(^|/)__MACOSX(/|$)#',
        '#^uploads/(products/\d+/|og/product-\d|collections/collection-\d|settings/.+\.(webp|jpg|jpeg|png|svg|ico))#',
    ],
];
