<?php
defined('SKYFR') || exit;

return [
    ['name' => 'home', 'method' => 'GET', 'path' => '/', 'controller' => 'home.php', 'view' => 'home.php', 'body_class' => 'home'],
    ['name' => 'shop', 'method' => 'GET', 'path' => '/shop', 'controller' => 'listing.php', 'view' => 'listing.php', 'body_class' => 'listing shop'],
    ['name' => 'collections.index', 'method' => 'GET', 'path' => '/collections', 'controller' => 'collections.php', 'view' => 'collections-index.php', 'body_class' => 'collections'],
    ['name' => 'gender.him', 'method' => 'GET', 'path' => '/for-him', 'controller' => 'listing.php', 'view' => 'listing.php', 'preset' => ['gender' => 'him'], 'body_class' => 'listing gender'],
    ['name' => 'gender.her', 'method' => 'GET', 'path' => '/for-her', 'controller' => 'listing.php', 'view' => 'listing.php', 'preset' => ['gender' => 'her'], 'body_class' => 'listing gender'],
    ['name' => 'gender.unisex', 'method' => 'GET', 'path' => '/unisex', 'controller' => 'listing.php', 'view' => 'listing.php', 'preset' => ['gender' => 'unisex'], 'body_class' => 'listing gender'],
    ['name' => 'new', 'method' => 'GET', 'path' => '/new-arrivals', 'controller' => 'listing.php', 'view' => 'listing.php', 'preset' => ['sort' => 'newest'], 'body_class' => 'listing merch'],
    ['name' => 'best', 'method' => 'GET', 'path' => '/best-sellers', 'controller' => 'listing.php', 'view' => 'listing.php', 'preset' => ['sort' => 'best'], 'body_class' => 'listing merch'],
    ['name' => 'sale', 'method' => 'GET', 'path' => '/sale', 'controller' => 'listing.php', 'view' => 'listing.php', 'preset' => ['on_sale' => '1'], 'body_class' => 'listing merch'],
    ['name' => 'search', 'method' => 'GET', 'path' => '/search', 'controller' => 'search.php', 'view' => 'listing.php', 'robots' => 'noindex,follow', 'body_class' => 'listing search'],
    ['name' => 'quiz', 'method' => 'GET', 'path' => '/scent-finder', 'controller' => 'quiz.php', 'view' => 'quiz.php', 'body_class' => 'quiz'],
    ['name' => 'quiz.result', 'method' => 'GET', 'path' => '/scent-finder/result', 'controller' => 'quiz.php', 'view' => 'quiz-result.php', 'robots' => 'noindex,follow', 'body_class' => 'quiz quiz-result'],
    ['name' => 'cart', 'method' => 'GET', 'path' => '/cart', 'controller' => 'cart.php', 'view' => 'cart.php', 'robots' => 'noindex,follow', 'body_class' => 'cart'],
    ['name' => 'checkout', 'method' => 'GET', 'path' => '/checkout', 'controller' => 'checkout.php', 'view' => 'checkout.php', 'robots' => 'noindex,follow', 'body_class' => 'checkout'],
    ['name' => 'checkout.store', 'method' => 'POST', 'path' => '/checkout', 'controller' => 'checkout-submit.php', 'view' => null, 'robots' => 'noindex,follow', 'body_class' => 'checkout'],
    ['name' => 'track', 'method' => 'GET|POST', 'path' => '/track', 'controller' => 'track.php', 'view' => 'track.php', 'body_class' => 'track'],
    ['name' => 'page.faq', 'method' => 'GET', 'path' => '/faq', 'controller' => 'page.php', 'view' => 'page-faq.php', 'body_class' => 'page page-faq'],
    ['name' => 'page.show', 'method' => 'GET', 'path' => ['/about', '/shipping', '/returns', '/privacy', '/terms'], 'controller' => 'page.php', 'view' => 'page.php', 'body_class' => 'page'],
    ['name' => 'contact', 'method' => 'GET|POST', 'path' => '/contact', 'controller' => 'contact.php', 'view' => 'contact.php', 'body_class' => 'contact'],
    ['name' => 'newsletter.unsub', 'method' => 'GET', 'path' => '/unsubscribe', 'controller' => 'newsletter.php', 'view' => 'simple.php', 'robots' => 'noindex,follow', 'body_class' => 'simple'],
    ['name' => 'sitemap', 'method' => 'GET', 'path' => '/sitemap.xml', 'controller' => 'sitemap.php', 'view' => null, 'robots' => 'noindex,follow'],
    ['name' => 'api.session', 'method' => 'GET', 'path' => '/api/session', 'controller' => 'api/session.php', 'view' => null],
    ['name' => 'api.cart.get', 'method' => 'GET', 'path' => '/api/cart', 'controller' => 'api/cart.php', 'view' => null],
    ['name' => 'api.cart.add', 'method' => 'POST', 'path' => '/api/cart/add', 'controller' => 'api/cart.php', 'view' => null],
    ['name' => 'api.cart.update', 'method' => 'POST', 'path' => '/api/cart/update', 'controller' => 'api/cart.php', 'view' => null],
    ['name' => 'api.cart.remove', 'method' => 'POST', 'path' => '/api/cart/remove', 'controller' => 'api/cart.php', 'view' => null],
    ['name' => 'api.cart.coupon', 'method' => 'POST', 'path' => '/api/cart/coupon', 'controller' => 'api/cart.php', 'view' => null],
    ['name' => 'api.suggest', 'method' => 'GET', 'path' => '/api/search-suggest', 'controller' => 'api/search.php', 'view' => null],
    ['name' => 'api.newsletter', 'method' => 'POST', 'path' => '/api/newsletter', 'controller' => 'api/newsletter.php', 'view' => null],
    ['name' => 'collections.show', 'method' => 'GET', 'path' => '/collections/{slug}', 'controller' => 'listing.php', 'view' => 'listing.php', 'where' => ['slug' => 'slug'], 'preset' => ['collection' => '{slug}'], 'body_class' => 'listing collection'],
    ['name' => 'scent.show', 'method' => 'GET', 'path' => '/scent/{slug}', 'controller' => 'listing.php', 'view' => 'listing.php', 'where' => ['slug' => 'slug'], 'preset' => ['family' => '{slug}'], 'body_class' => 'listing scent'],
    ['name' => 'product.show', 'method' => 'GET', 'path' => '/product/{slug}', 'controller' => 'product.php', 'view' => 'product.php', 'where' => ['slug' => 'slug'], 'body_class' => 'product'],
    ['name' => 'review.store', 'method' => 'POST', 'path' => '/product/{slug}/review', 'controller' => 'review-submit.php', 'view' => null, 'where' => ['slug' => 'slug'], 'robots' => 'noindex,follow', 'body_class' => 'product'],
    ['name' => 'order.show', 'method' => 'GET', 'path' => '/order/{order}', 'controller' => 'confirmation.php', 'view' => 'confirmation.php', 'where' => ['order' => 'order'], 'robots' => 'noindex,follow', 'body_class' => 'confirmation'],
    ['name' => 'notfound', 'method' => 'GET|POST', 'path' => '*', 'controller' => 'notfound.php', 'view' => '404.php', 'robots' => 'noindex,follow', 'body_class' => 'error'],
];
